// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pacnjactjhmvdszasicm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBhY25qYWN0amhtdmRzemFzaWNtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ0MzIwNTQsImV4cCI6MjA1MDAwODA1NH0.t5dfdb9PoP0MVdzcIF179pO9Ys6LCgb2yC362J-Es8Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);